import turtle
import math
scrn = turtle.Screen()
scrn.bgcolor("lavender")
pen = turtle.Turtle()
pen.color("yellow")
pen.pensize(2)
pen.shape("circle")
pen.right(90)
pen.forward(50)
pen.left(90)
pen.forward(50)
pen.left(90)
pen.forward(50)
pen.left(90)
pen.forward(50)
dis = math.sqrt(50*50/2)
pen.right(135)
pen.forward(dis)
pen.right(90)
pen.forward(dis)
scrn.exitonclick()